# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
- dev
- releases/*

pool:
  name: default

steps:
- task: SonarQubePrepare@4
  inputs:
    SonarQube: 'sonarqueue'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'NFT-JAPAN_NFT-JAPAN-FRONTEND-SSR'
    cliSources: '.'
    extraProperties: |
      # Additional properties that will be passed to the scanner, 
      # Put one key=value per line, example:
      # sonar.exclusions=**/*.bin
      sonar.core.serverBaseURL=http://sonar.dev.nftal.io
- task: SonarQubeAnalyze@4
- task: SonarQubePublish@4
  inputs:
    pollingTimeoutSec: '300'