version: "3.3"
services:
  react-build:
    build:
      context: ../../
      dockerfile: Dockerfile
    command:
      - /bin/bash
      - -c
      - |
        cp -R build output
    volumes:
      - ../../build:/app/output
    environment:
      - REACT_APP_ENV
    restart: "no"

